/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_snake_Snake */

#ifndef _Included_com_example_snake_Snake
#define _Included_com_example_snake_Snake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_snake_Snake
 * Method:    getDirFromBoard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_snake_Snake_getDirFromBoard
  (JNIEnv *, jobject);

/*
 * Class:     com_example_snake_Snake
 * Method:    updateScore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_snake_Snake_updateScore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_snake_Snake
 * Method:    msgBoard
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_snake_Snake_msgBoard
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_snake_Snake
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_snake_Snake_openDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_example_snake_Snake
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_snake_Snake_closeDevice
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
